// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsxVBi51plefaG4NxiiOWmjKn1TYZ9F1Q',
    appId: '1:560636044080:web:0a87cff05cb240db2c5ef5',
    messagingSenderId: '560636044080',
    projectId: 'root-e1f47',
    authDomain: 'root-e1f47.firebaseapp.com',
    databaseURL: 'https://root-e1f47.firebaseio.com',
    storageBucket: 'root-e1f47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwLDUf3hmG-d_MVlTSKlcf7Ir4J56rdIw',
    appId: '1:560636044080:android:61f40c8e2b7bc6382c5ef5',
    messagingSenderId: '560636044080',
    projectId: 'root-e1f47',
    databaseURL: 'https://root-e1f47.firebaseio.com',
    storageBucket: 'root-e1f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDSCNNGd_FI7Z87Yizk8xEy7efiLIWqYw',
    appId: '1:560636044080:ios:abcd09e2265e60b32c5ef5',
    messagingSenderId: '560636044080',
    projectId: 'root-e1f47',
    databaseURL: 'https://root-e1f47.firebaseio.com',
    storageBucket: 'root-e1f47.appspot.com',
    androidClientId: '560636044080-2shdp9o19n7nhe4nhesrmn3rv6bucnnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDSCNNGd_FI7Z87Yizk8xEy7efiLIWqYw',
    appId: '1:560636044080:ios:abcd09e2265e60b32c5ef5',
    messagingSenderId: '560636044080',
    projectId: 'root-e1f47',
    databaseURL: 'https://root-e1f47.firebaseio.com',
    storageBucket: 'root-e1f47.appspot.com',
    androidClientId: '560636044080-2shdp9o19n7nhe4nhesrmn3rv6bucnnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEEnu6UPEHqfqoF-1mlqPxxgc1Hx_OZHo',
    appId: '1:560636044080:web:19da82f9fa64b20b2c5ef5',
    messagingSenderId: '560636044080',
    projectId: 'root-e1f47',
    authDomain: 'root-e1f47.firebaseapp.com',
    databaseURL: 'https://root-e1f47.firebaseio.com',
    storageBucket: 'root-e1f47.appspot.com',
  );

}