// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD--EKLO_fHi09ICNb0IHiNMe1Kg8tam1Y',
    appId: '1:614344629280:web:04428638c957bd7c683045',
    messagingSenderId: '614344629280',
    projectId: 'artmini-f5ca4',
    authDomain: 'artmini-f5ca4.firebaseapp.com',
    databaseURL: 'https://artmini-f5ca4-default-rtdb.firebaseio.com',
    storageBucket: 'artmini-f5ca4.firebasestorage.app',
    measurementId: 'G-NB86BECGK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADIBd16FAuBqz4vujHC68ibz4u_Lewh5I',
    appId: '1:1010633075142:android:74ddbbfecacd3f10c82ac7',
    messagingSenderId: '1010633075142',
    projectId: 'hivesolar-staging-10f3b',
    storageBucket: 'hivesolar-staging-10f3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxo7KTXCozWwfRRQWiIRjj38x3MW-8hfQ',
    appId: '1:614344629280:ios:b862342ae0edab39683045',
    messagingSenderId: '614344629280',
    projectId: 'artmini-f5ca4',
    databaseURL: 'https://artmini-f5ca4-default-rtdb.firebaseio.com',
    storageBucket: 'artmini-f5ca4.firebasestorage.app',
    iosBundleId: 'com.hive.hivesolar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxo7KTXCozWwfRRQWiIRjj38x3MW-8hfQ',
    appId: '1:614344629280:ios:b862342ae0edab39683045',
    messagingSenderId: '614344629280',
    projectId: 'artmini-f5ca4',
    databaseURL: 'https://artmini-f5ca4-default-rtdb.firebaseio.com',
    storageBucket: 'artmini-f5ca4.firebasestorage.app',
    iosBundleId: 'com.hive.hivesolar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBACj3mXiwDEBZne5LukQhikIRPQIsxnjw',
    appId: '1:614344629280:web:6ff7d26de360b0a6683045',
    messagingSenderId: '614344629280',
    projectId: 'artmini-f5ca4',
    authDomain: 'artmini-f5ca4.firebaseapp.com',
    databaseURL: 'https://artmini-f5ca4-default-rtdb.firebaseio.com',
    storageBucket: 'artmini-f5ca4.firebasestorage.app',
    measurementId: 'G-X6235M5E7B',
  );

}